trigger:
- '*'

pool:
  vmImage: 'ubuntu-20.04'
  demands:
  - npm #especifica que necesitamosnpm instalado en el sistme

variables:
  buildConfiguration: 'Release'

steps: #conjutno de build task
- task: UseDotNet@2 # isntala las herramintas de compilacion requeridas para ejecutar el agente 
  displayName: 'Use .NET SDK 6.x'
  inputs:
    packageType: sdk
    version: '6.x'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt' #esto es para que corra en consola, se lo peude poner de esta forma o como pongo abajo #este comando -> almacena info sobre el nombre de la pipeline, el id, el nombre de la build (por defecto es la fecha)
#- task: cmdLine@2 pero nose que mas hbaria que agregar para que haga ese comadno xd
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2 #mapea con el comando dotnet 
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore' #para reiniciar o instalar las dependencias 
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build' # para buildear el rpecto
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'